name: ci

on:
    push:
        branches:
            - main
            - develop
            - ci
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        name: "Lint | PHP ${{ matrix.php-version }}"
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.2"
                    - "8.3"
                    - "8.4"
        steps:
            - uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"
                  tools: composer:v2

            - name: Validate composer.json
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-php${{ matrix.php-version }}-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-php${{ matrix.php-version }}-

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-interaction

            - name: phpcs
              run: php vendor/bin/phpcs

            - name: phpstan
              run: php vendor/bin/phpstan analyze

    test:
        runs-on: ubuntu-latest
        name: "Test | PHP ${{ matrix.php-version }} | Laravel ${{ matrix.laravel-version }}"
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.2"
                    - "8.3"
                    - "8.4"
                laravel-version:
                    - "12"
                    - "13"
                exclude:
                    - php-version: "8.2"
                      laravel-version: "13"
        steps:
            - uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"
                  tools: composer:v2

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-php${{ matrix.php-version }}-${{ hashFiles('composer.json') }}-laravel${{ matrix.laravel-version }}
                  restore-keys: |
                      ${{ runner.os }}-php${{ matrix.php-version }}-

            - name: Pin laravel
              run: composer require --no-update --dev --no-progress --no-interaction --prefer-dist laravel/framework:^${{ matrix.laravel-version }}

            - name: Install dependencies
              run: composer update --no-progress --no-interaction --prefer-dist

            - name: Run test suite
              run: php vendor/bin/phpunit --no-coverage

            - name: Run e2e tests
              run: ./vendor/bin/phpstan analyse --configuration=e2e/phpstan-e2e.neon --error-format=json  | ./e2e/test-runner

            - name: Run phpbench
              run: ./vendor/bin/phpbench run

    coverage:
        runs-on: ubuntu-latest
        name: "Coverage | PHP ${{ matrix.php-version }}"
        strategy:
            matrix:
                php-version:
                    - "8.3"
        steps:
            - uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: "${{ matrix.php-version }}"
                  tools: composer:v2

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-php${{ matrix.php-version }}-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-php${{ matrix.php-version }}-

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-interaction

            - name: Run test suite with coverage
              run: php vendor/bin/phpunit --coverage-text

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v6
              with:
                  files: clover.xml
